<a href="https://colab.research.google.com/github/31indianaSKKU/DeepLearning_2022FALL/blob/main/DeepLearning2022_week13_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CNN(1)

## 1 convolution (합성곱 연산 및 교차상관)

In [1]:
import numpy as np

In [2]:
w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [3]:
w

array([2, 1, 5, 3])

In [4]:
x

array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [5]:
print(x)

[2 8 3 7 1 2 0 4 5]


In [11]:
print(type(x))
print(type(w))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
w_r = np.flip(w)
print(w_r)

[3 5 1 2]


In [21]:
w[0:4:2]

array([2, 5])

In [17]:
#개인연습
w[0:4:1]

array([2, 1, 5, 3])

In [18]:
#개인연습
w[0:3:2]

array([2, 5])

In [19]:
#개인연습
w[0:3:1]

array([2, 1, 5])

In [14]:
#개인연습
x[0:4:2]

array([2, 3])

In [22]:
#개인연습
x[0:9:1]

array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [24]:
#개인연습
x[0:8:1]

array([2, 8, 3, 7, 1, 2, 0, 4])

In [ ]:
for i in range(6):
    print(np.dot(x[i:i+4], w_r))     #??????????????????????????????????

63
48
49
28
21
20


In [27]:
from scipy.signal import convolve

In [28]:
convolve(x, w, mode='valid')

array([63, 48, 49, 28, 21, 20])

In [29]:
from scipy.signal import correlate

In [ ]:
correlate(x, w, mode='valid')

array([48, 57, 24, 25, 16, 39])

In [30]:
correlate(x, w, mode='full')

array([ 6, 34, 51, 48, 57, 24, 25, 16, 39, 29, 13, 10])

In [31]:
correlate(x, w, mode='same')

array([34, 51, 48, 57, 24, 25, 16, 39, 29])

## 2차원 배열 합성곱.

In [32]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
w = np.array([[2, 0], [0, 0]])

In [33]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
w

array([[2, 0],
       [0, 0]])

In [35]:
from scipy.signal import correlate2d

correlate2d(x, w, mode='valid')

array([[ 2,  4],
       [ 8, 10]])

In [36]:
np.flip(w)

array([[0, 0],
       [0, 2]])

In [37]:
from scipy.signal import convolve2d

convolve2d(x, w, mode='valid')

array([[10, 12],
       [16, 18]])

In [38]:
correlate2d(x, w, mode='same')

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [39]:
import tensorflow as tf

In [40]:
x_4d = x.astype(np.float).reshape(1, 3, 3, 1)
w_4d = w.reshape(2, 2, 1, 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [41]:
c_out = tf.nn.conv2d(x_4d, w_4d, strides=1, padding='SAME')
c_out.numpy().reshape(3, 3)

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

## 2 pooling

In [42]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
x = x.reshape(1, 4, 4, 1)

In [43]:
p_out = tf.nn.max_pool2d(x, ksize=2, strides=2, padding='VALID')
p_out.numpy().reshape(2, 2)

array([[ 6.,  8.],
       [14., 16.]], dtype=float32)

## 3 relu

In [44]:
def relu(x):
    return np.maximum(x, 0)

In [45]:
x = np.array([-1, 2, -3, 4, -5])

relu(x)

array([0, 2, 0, 4, 0])

In [46]:
r_out = tf.nn.relu(x)
r_out.numpy()

array([0, 2, 0, 4, 0])